server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: Narainox@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


